<center>
<h1>PROGRAMMING ASSIGNMENT<h1>
<h1>CSC-343 ARTIFICIAL INTELLIGENCE<h1>
<h1> PROGRAMMING ASSIGNMENT 5</h1>
</center>

<br/>
<hr/>
<br/>

**Question 1**. 

Given a body of text  with $n$  <u>_unique_</u>  tokens (say The Comedy of Errors by Shakespeare with ~3707 unique tokens) create an $n \times n$ matrix $Cooccurences$ such that $Cooccurences[i, j]$ is equal to the number of times the word $i$ <u>_preceeds_</u> word $j$ within a window length of $k$ tokens. 

For example, `text = "To be or not to be"` has $n=4$; for $k = 2,~Cooccurence_{~text}~$should be:

<br/>

\begin{bmatrix} 
	 & to & be & or & not \\
	to & 0 & 2 & 1 & 0\\
	be & 0 & 0 & 1 & 1\\
	or & 1 & 0 & 0 & 1\\
	not & 1 & 1 & 0 & 0\\
	\end{bmatrix}

In [6]:
import requests

def tokenize(text):
  import spacy
  nlp = spacy.load("en_core_web_sm")
  all_tokens = [token.text.lower() for token in nlp(text)]
  vocab = set(all_tokens)
  return all_tokens, vocab

response = requests.get('https://shakespeare.folger.edu/downloads/txt/the-comedy-of-errors_TXT_FolgerShakespeare.txt')

text = response.content.decode()

all_tokens, vocab = tokenize(text)

In [7]:
len(all_tokens), len(vocab)
vocabList = list(vocab)

In [8]:
import pandas as pd

df = pd.DataFrame(index = vocab, columns = vocab)
df.head()

,works</a></p,blush,red');--wp,bg,spaces</a></li,tested,celebrating,',sees,secret,...,"plays""><span",style,artists,cyan,valid,than,hamlet,u-1/4@desktop,villainous,"src=""https://images.folger.edu"
works</a></p,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
blush,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
red');--wp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
spaces</a></li,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df[:] = 0

def kthMatrix(k):
  kthList = [-1] * k

  for word in all_tokens:
    for prevWord in kthList:
      if prevWord == -1:
        continue
      df[word][prevWord] = df[word][prevWord] +1

    kthList.pop(0)
    kthList.append(word)

kthMatrix(2)
df.head()

,works</a></p,blush,red');--wp,bg,spaces</a></li,tested,celebrating,',sees,secret,...,"plays""><span",style,artists,cyan,valid,than,hamlet,u-1/4@desktop,villainous,"src=""https://images.folger.edu"
works</a></p,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
blush,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
red');--wp,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bg,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
spaces</a></li,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
# TESTING #
import pandas as pd

testTokens = ["to", "be", "or", "not", "to", "be"]
testVocab = ["to", "be", "or", "not"]

df = pd.DataFrame(index = testVocab, columns = testVocab)
df[:] = 0

def kthMatrix(k):
  kthList = [-1] * k

  for word in testTokens:
    for prevWord in kthList:
      if prevWord == -1:
        continue

      df[word][prevWord] = df[word][prevWord] +1
    kthList.pop(0)
    kthList.append(word)

kthMatrix(2)
df.head()

    to be or not
to   0  2  1   0
be   0  0  1   1
or   1  0  0   1
not  1  1  0   0